Repository CycloneDX/cdxgen, pull requests merged in 2023-09, with the labels that each got.

#514 Few adhoc bug fixes. 9.7.0 prep
  ADVANCED.md
  binary.js
  data/queries-win.json
  data/queries.json
  display.js
  evinser.js
  index.js
  package-lock.json
  package.json
  utils.js
  utils.test.js
Labels: help wanted, Ready for QA

#532 Feature/501 dependency tree for dotnet
  index.js
  utils.js
  utils.test.js
Labels: enhancement

#539 .NET Direct Pkg Dependencies
  test/data/project.assets.json
  utils.js
  utils.test.js
Labels: Ready for QA

#535 Use the new atom frontends for C
  ADVANCED.md
  README.md
  bin/cdxgen.js
  display.js
  index.js
  package-lock.json
  package.json
  test/data/bun.lockb
  test/data/cmakes/CMakeLists.txt
  test/data/cmakes/conanfile.txt
  test/data/cmakes/mongoc-config.cmake
  test/data/msgpack.mk
  utils.js
  utils.test.js
Labels: Ready for QA
