Repository CycloneDX/cdxgen, pull requests merged in 2024-02, with the labels that each got.

#696 feat: oci image support for multiple src files
  docker.js
  docker.test.js
  index.js
Labels: enhancement

#884 Ruby improvements
  .vscode/settings.json
  README.md
  ci/Dockerfile
  ci/Dockerfile-deno
  ci/Dockerfile-fedora
  ci/Dockerfile-ppc64
  deno.json
  docker.js
  index.js
  package-lock.json
  package.json
  test/data/Gemfile1.lock
  test/data/Gemfile2.lock
  utils.js
  utils.test.js
Labels: enhancement, sponsored

#887 Track remote and revision for Gemfile.lock
  package-lock.json
  package.json
  test/data/Gemfile4.lock
  utils.js
  utils.test.js
Labels: enhancement, sponsored

#890 Reliably track gem packages with the same name
  package-lock.json
  package.json
  test/data/Gemfile5.lock
  test/data/Gemfile6.lock
  utils.js
  utils.test.js
Labels: enhancement, sponsored

#893 docs: add example for git authentication
  README.md
  docs/README.md
  docs/SERVER.md
Labels: documentation
