Repository CycloneDX/cdxgen, pull requests merged in 2024-07, with the labels that each got.

#1202 Multi project types
  .codacy.yml
  .github/workflows/dockertests.yml
  .github/workflows/java-reachables-test.yml
  .github/workflows/repotests.yml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  bin/cdxgen.js
  bin/repl.js
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  contrib/lima/cdxgen-opensuse.yaml
  deno.json
  display.js
  docs/ADVANCED.md
  docs/CLI.md
  evinser.js
  index.js
  jsr.json
  package.json
  pnpm-lock.yaml
  postgen.js
  server.js
  types/display.d.ts
  types/display.d.ts.map
  types/evinser.d.ts
  types/evinser.d.ts.map
  types/index.d.ts.map
  types/postgen.d.ts
  types/postgen.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: enhancement, Ready for QA, refactor, mode:cli, mode:server, mode:repl

#1205 Fix issues with multi-threaded Gradle sbom gen
  index.js
  test/gradle-dep-parallel.out
  test/gradle-prop-parallel.out
  utils.js
  utils.test.js
Labels: Ready for QA

#1207 Do not aggressively exclude while dealing with java projects
  index.js
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA

#1211 Update atom to get parsedeps improvements
  ci/Dockerfile
  contrib/lima/cdxgen-opensuse.yaml
  deno.json
  package.json
  pnpm-lock.yaml
  types/index.d.ts.map
  types/utils.d.ts.map
  utils.js
Labels: Ready for QA, possibly breaking, lang:python

#1219 Support for Rancher Desktop on mac
  .github/workflows/npm-release.yml
  binary.js
  docker.js
  docs/ADVANCED.md
  types/binary.d.ts.map
  types/docker.d.ts
  types/docker.d.ts.map
  utils.test.js
Labels: enhancement, mode:cli, rancher

#1217 Support for invoking multiple package managers for java
  bin/repl.js
  display.js
  index.js
  types/index.d.ts.map
  types/utils.d.ts.map
  utils.js
Labels: Ready for QA, sponsored, possibly breaking, lang:java

#1228 In universal mode, safely ignore directories from container export
  .github/workflows/dockertests.yml
  .github/workflows/repotests.yml
  deno.json
  docker.js
  index.js
  jsr.json
  package.json
  types/docker.d.ts.map
  types/index.d.ts.map
Labels: lang:container

#1236 Remove python duplicate tree
  index.js
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
Labels: possibly breaking, lang:python

#1235 Fixes issue for Global Assembly Cache DLL without version numbers
  README.md
  types/utils.d.ts.map
  utils.js
Labels: lang:dotnet

#1238 Evinse occurrence evidence was broken since language is a list in 10.8.x
  deno.json
  evinser.js
  jsr.json
  package.json
  pnpm-lock.yaml
  types/evinser.d.ts.map
  utils.test.js
Labels: lang:python, evinse

#1241 Fix for empty environment variables causing validation failures
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  deno.json
  index.js
  jsr.json
  package.json
  types/index.d.ts.map
  types/utils.d.ts.map
  utils.js
Labels: lang:python

#1250 Disable formulation collection by default
  bin/cdxgen.js
  deno.json
  index.js
  jsr.json
  package.json
  types/index.d.ts.map
  types/utils.d.ts.map
Labels: security, formulation

#1266 Fixes 1264
  index.js
  types/index.d.ts.map
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA, lang:java

#1277 docs(server): update to highlight that comma separated types are supported
  docs/SERVER.md
Labels: documentation, mode:server

#1274 feat(server): improve logging
  server.js
Labels: enhancement, mode:server

#1280 Feat: New safe pip install to recover partial dependency tree
  .github/workflows/repotests.yml
  bin/cdxgen.js
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  deno.json
  index.js
  jsr.json
  package.json
  pnpm-lock.yaml
  types/evinser.d.ts
  types/index.d.ts.map
  types/server.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA, sponsored, lang:python

#1283 yarn v1 lockfile with quoted keys were not working
  test/data/yarn_locks/yarnv1-empty.lock
  types/evinser.d.ts
  types/utils.d.ts.map
  types/validator.d.ts.map
  utils.js
  utils.test.js
  validator.js
Labels: lang:node, yarn
