Repository CycloneDX/cdxgen, pull requests merged in 2024-08, with the labels that each got.

#1290 Invoke atom parsedeps only in deep mode or as a fallback
  binary.js
  deno.json
  index.js
  jsr.json
  package.json
  types/binary.d.ts.map
  types/index.d.ts.map
Labels: sponsored, possibly breaking, lang:python

#1275 build: restore vscode settings
  .vscode/extensions.json
  .vscode/settings.json
Labels: build

#1292 build: add lint-staged
  package.json
Labels: build

#1298 Support for excluding individual package managers in java
  .github/workflows/repotests.yml
  index.js
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
Labels: lang:java

#1299 sdkman support
  .github/workflows/repotests.yml
  bin/cdxgen.js
  bin/repl.js
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  deno.json
  display.js
  docs/PROJECT_TYPES.md
  envcontext.js
  envcontext.test.js
  jsr.json
  package.json
  postgen.js
  pregen.js
  types/display.d.ts
  types/display.d.ts.map
  types/envcontext.d.ts
  types/envcontext.d.ts.map
  types/postgen.d.ts
  types/postgen.d.ts.map
  types/pregen.d.ts
  types/pregen.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
Labels: sponsored, lang:java

#1301 sdkman in container
  .dockerignore
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  contrib/lima/cdxgen-opensuse.yaml
  envcontext.js
  package.json
  types/envcontext.d.ts.map
Labels: lang:container, lang:python, lang:java

#1303 Adds occurrence evidence for poetry projects
  contrib/rebuild-sqlite3.sh
  evinser.js
  index.js
  postgen.js
  types/evinser.d.ts.map
  types/index.d.ts.map
  types/postgen.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: lang:python

#1306 Required only filter for python was too aggressive
  .github/workflows/repotests.yml
  deno.json
  jsr.json
  package.json
  postgen.js
  types/postgen.d.ts.map
  types/utils.d.ts.map
  utils.js
Labels: bug, Ready for QA, lang:python

#1312 build: use labels for changleog release section generation
  .github/release.yml
Labels: build

#1320 Feat: Add support for pixi package manager
  index.js
  package.json
  pnpm-lock.yaml
  types/index.d.ts
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: lang:python, pixi
