Repository CycloneDX/cdxgen, pull requests merged in 2024-09, with the labels that each got.

#1349 Force go mod graph even when go list errors out
  deno.json
  index.js
  jsr.json
  package.json
  types/index.d.ts
  types/index.d.ts.map
  types/utils.d.ts.map
Labels: sponsored, lang:go

#1350 Update packages. Tuned down a warning
  deno.json
  jsr.json
  package.json
  pnpm-lock.yaml
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA, lang:node

#1352 Tune down a log
  index.js
  types/index.d.ts.map
Labels: lang:java

#1354 feat: gomod direct detection
  .github/workflows/repotests.yml
  ADVANCED.md
  README.md
  docs/CLI.md
  docs/ENV.md
  docs/README.md
  docs/SERVER.md
  index.js
  test/data/go-dvwa.mod
  test/data/go-syft.mod
  test/data/gomod-dvwa-graph.txt
  test/data/gomod-syft-graph.txt
  types/index.d.ts
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  types/validator.d.ts.map
  utils.js
  utils.test.js
  validator.js
Labels: sponsored, possibly breaking, lang:go

#1356 Improve partial dependency tree detection
  deno.json
  index.js
  jsr.json
  package.json
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
  validator.js
Labels: sponsored, lang:python

#1357 Feat: Add support for different Node versions (NVM support)
  .github/workflows/repotests.yml
  envcontext.js
  envcontext.test.js
  pregen.js
  types/envcontext.d.ts
  types/envcontext.d.ts.map
  types/pregen.d.ts
  types/pregen.d.ts.map
  types/utils.d.ts.map
  utils.js
Labels: sponsored, lang:node

#1365 [Gradle] Correctly identify all modules' group and version
  index.js
  utils.js
  utils.test.js
Labels: Ready for QA, gradle

#1368 [Gradle] Resolve gradle module from npm package
  .github/workflows/repotests.yml
  docs/ENV.md
  index.js
  utils.js
  utils.test.js
Labels: Ready for QA, gradle

#1374 Recover dependency tree from nuspec files
  README.md
  test/data/xunit.nuspec
  test/data/xunit.runner.utility.nuspec
  test/diff/repos.csv
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: sponsored, lang:dotnet

#1379 [Gradle] Fixed a problem with scoped NPM packages while resolving modules from NPM
  .github/workflows/repotests.yml
  index.js
Labels: gradle

#1384 Typescript 5.6.x with the latest atom
  biome.json
  deno.json
  package.json
  pnpm-lock.yaml
Labels: lang:node

#1386 Poetry root list from pyproject.toml
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/helpers/validator.js
  tsconfig.json
  types/analyzer.d.ts.map
  types/binary.d.ts.map
  types/cbomutils.d.ts.map
  types/db.d.ts.map
  types/display.d.ts.map
  types/docker.d.ts.map
  types/envcontext.d.ts.map
  types/evinser.d.ts.map
  types/index.d.ts.map
  types/lib/cli/index.d.ts
  types/lib/cli/index.d.ts.map
  types/lib/evinser/evinser.d.ts
  types/lib/evinser/evinser.d.ts.map
  types/lib/helpers/analyzer.d.ts
  types/lib/helpers/analyzer.d.ts.map
  types/lib/helpers/cbomutils.d.ts
  types/lib/helpers/cbomutils.d.ts.map
  types/lib/helpers/db.d.ts
  types/lib/helpers/db.d.ts.map
  types/lib/helpers/display.d.ts
  types/lib/helpers/display.d.ts.map
  types/lib/helpers/envcontext.d.ts
  types/lib/helpers/envcontext.d.ts.map
  types/lib/helpers/protobom.d.ts
  types/lib/helpers/protobom.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
  types/lib/helpers/validator.d.ts
  types/lib/helpers/validator.d.ts.map
  types/lib/managers/binary.d.ts
  types/lib/managers/binary.d.ts.map
  types/lib/managers/docker.d.ts
  types/lib/managers/docker.d.ts.map
  types/lib/managers/piptree.d.ts
  types/lib/managers/piptree.d.ts.map
  types/lib/server/server.d.ts
  types/lib/server/server.d.ts.map
  types/lib/stages/postgen/postgen.d.ts
  types/lib/stages/postgen/postgen.d.ts.map
  types/lib/stages/pregen/pregen.d.ts
  types/lib/stages/pregen/pregen.d.ts.map
  types/piptree.d.ts.map
  types/postgen.d.ts.map
  types/pregen.d.ts.map
  types/protobom.d.ts.map
  types/server.d.ts.map
  types/utils.d.ts.map
  types/validator.d.ts.map
Labels: sponsored, lang:python

#1383 [Gradle] Scanning of all modules fixed
  .github/workflows/repotests.yml
  docs/ENV.md
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
Labels: Ready for QA, gradle
