Repository CycloneDX/cdxgen, pull requests merged in 2024-05, with the labels that each got.

#1036 Use node 22 via nvm in docker. Enable NODE_COMPILE_CACHE
  .github/workflows/dockertests.yml
  .gitignore
  binary.js
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-fedora
  ci/Dockerfile-ppc64
  deno.json
  docker-compose.yml
  docker.js
  docs/ADVANCED.md
  index.js
  jsr.json
  package-lock.json
  package.json
  types/binary.d.ts.map
  types/docker.d.ts.map
  types/index.d.ts.map
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA, edge

#1057 docs: add project types
  README.md
  docs/PROJECT_TYPES.md
  docs/_sidebar.md
Labels: documentation

#1056 docs: add NODE_OPTIONS
  docs/ENV.md
Labels: documentation

#1059 docs: update community support
  README.md
Labels: documentation

#1058 build: add codeowners file
  .github/CODEOWNERS
Labels: build

#1060 docs: link to contribute labels
  README.md
Labels: documentation

#1073 feat(docker): default to docker.io registry
  docker.js
Labels: enhancement, container

#1071 docs: enterprise and community support
  README.md
  docs/SUPPORT.md
  docs/_sidebar.md
Labels: documentation

#1070 docs: remove unused media. should be in `_media/` folder
  README.md
  cdxgen.png
  docs/PROJECT_TYPES.md
  docs/callstack-evidence.png
  docs/cdxgen-tree.jpg
  docs/occurrence-evidence.png
  docs/saasbom-services.png
  docs/why-cdxgen.jpg
  sbom-sign.jpg
Labels: documentation

#1069 docs: env variables
  README.md
  docs/ENV.md
  docs/_sidebar.md
Labels: documentation

#1068 docs: type args ref to docs
  README.md
  bin/cdxgen.js
  docs/README.md
Labels: documentation

#1079 docs: add documentation section
  README.md
Labels: documentation

#1080 docs: update h1
  README.md
Labels: documentation

#1083 docs: fix broken `queries.json` link
  README.md
Labels: documentation

#1078 build: update contributors
  package.json
Labels: build

#1081 docs: use link labels
  README.md
Labels: documentation

#1087 feat: increase yargs terminal width
  bin/cdxgen.js
  bin/evinse.js
  bin/verify.js
  docs/CLI.md
Labels: enhancement

#1091 feat: increase yargs terminal width
  bin/cdxgen.js
  bin/evinse.js
  bin/verify.js
  docs/CLI.md
Labels: enhancement

#1096 Improved troubleshooting for go
  .github/workflows/nodejs.yml
  .github/workflows/repotests.yml
  .vscode/settings.json
  README.md
  binary.js
  ci/Dockerfile-deno
  contrib/deno/README.md
  deno.json
  docs/CLI.md
  index.js
  utils.js
  utils.test.js
Labels: Ready for QA, lang:go, runtime:deno

#1100 Adding The Installation Of Root Dependencies For Npm
  index.js
Labels: Ready for QA, possibly breaking, lang:node

#1102 cargo deep mode
  .github/FUNDING.yml
  .github/workflows/npm-release.yml
  bin/repl.js
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-fedora
  ci/Dockerfile-ppc64
  index.js
  test/data/zstd_sys-dc50c4de2e4e7df8.d
  types/binary.d.ts.map
  types/docker.d.ts
  types/docker.d.ts.map
  types/index.d.ts
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: enhancement, Ready for QA, lang:rust, possibly breaking

#1114 docs: fix repo link
  docs/index.html
Labels: documentation

#1111 build(biome): apply safe changes. add script to filter summary for errors only
  package.json
Labels: build

#1110 build(biome): update formatter options to ignore types/**
  biome.json
  types/analyzer.d.ts
  types/binary.d.ts
  types/cbomutils.d.ts
  types/db.d.ts
  types/display.d.ts
  types/docker.d.ts
  types/docker.d.ts.map
  types/envcontext.d.ts
  types/evinser.d.ts
  types/index.d.ts
  types/index.d.ts.map
  types/jest.config.d.ts
  types/piptree.d.ts
  types/postgen.d.ts
  types/protobom.d.ts
  types/server.d.ts
  types/utils.d.ts
  types/validator.d.ts
Labels: build

#1120 Adds new vulnerabilities command to the repl
  bin/repl.js
  display.js
  types/display.d.ts
  types/display.d.ts.map
Labels: enhancement, mode:repl

#1121 Update spdx schema. Update packages
  .github/workflows/java-reachables-test.yml
  data/spdx.schema.json
  deno.json
  package-lock.json
  package.json
  utils.test.js
Labels: Ready for QA
