Repository CycloneDX/cdxgen, pull requests merged in 2024-04, with the labels that each got.

#949 Cargo parent components from cargo.toml
  index.js
  test/data/Cargo3.toml
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: enhancement, Ready for QA, rust

#959 Include csproj files during restore
  index.js
Labels: sponsored

#961 Bundle dotnet sdk 8
  binary.js
  ci/Dockerfile
  ci/Dockerfile-deno
  index.js
  package-lock.json
  package.json
Labels: enhancement, sponsored

#966 docs: badges
  README.md
Labels: documentation

#968 docs: update downloads badge
  README.md
Labels: documentation

#989 chore(biome): fix unused template literals
  biome.json
  docker.js
  index.js
  validator.js
Labels: refactor

#991 chore(biome): fix no double equals
  bin/cdxgen.js
  biome.json
  display.js
  envcontext.js
  evinser.js
  index.js
  utils.js
  validator.js
Labels: refactor

#1007 Add support for executing dependencies task in parallel for Gradle
  index.js
  utils.js
Labels: enhancement, Ready for QA

#1026 Python cbom
  .github/workflows/repotests.yml
  bin/cdxgen.js
  bin/repl.js
  bun.lockb
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-fedora
  ci/Dockerfile-ppc64
  data/crypto-oid.json
  data/lic-mapping.json
  deno.json
  display.js
  evinser.js
  index.js
  jsr.json
  package-lock.json
  package.json
  utils.js
  utils.test.js
Labels: enhancement, help wanted, Ready for QA

#1028 Update atom. Regenerate types
  binary.js
  deno.json
  docs/ADVANCED.md
  evinser.js
  package-lock.json
  package.json
  types/display.d.ts
  types/display.d.ts.map
  types/evinser.d.ts.map
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
Labels: Ready for QA

#1029 Support for standard templates
  .github/workflows/repotests.yml
  README.md
  bin/cdxgen.js
  data/lic-mapping.json
  data/templates/README.md
  data/templates/asvs-4.0.3.cdx.json
  data/templates/bsimm-v13.cdx.json
  data/templates/masvs-2.0.0.cdx.json
  data/templates/nist-ssdf-1.1.cdx.json
  data/templates/pcissc-secure-slc-1.1.cdx.json
  data/templates/scvs-1.0.0.cdx.json
  data/templates/ssaf-DRAFT-2023-11.cdx.json
  docs/CLI.md
  docs/LESSON1.md
  docs/LESSON2.md
  docs/LESSON3.md
  docs/LESSON4.md
  docs/_sidebar.md
  postgen.js
  types/binary.d.ts.map
  types/evinser.d.ts.map
  types/postgen.d.ts
  types/postgen.d.ts.map
Labels: enhancement
