Repository CycloneDX/cdxgen, pull requests merged in 2024-06, with the labels that each got.

#1134 Switch to pnpm
  .github/workflows/dockertests.yml
  .github/workflows/java-reachables-test.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/npm-release.yml
  .github/workflows/python-atom-tests.yml
  .github/workflows/repotests.yml
  .github/workflows/snapshot-tests.yml
  README.md
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  deno.json
  jsr.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  types/evinser.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA

#1138 build: update biomejs
  analyzer.js
  biome.json
  package.json
  pnpm-lock.yaml
  utils.js
Labels: build

#1139 Feature/dotnet roll forward
  .github/workflows/dockertests.yml
  .github/workflows/repotests.yml
  docs/ADVANCED.md
  docs/ENV.md
  index.js
  test/data/mvn-dep-tree-simple.txt
  types/index.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA, sponsored, lang:dotnet, possibly breaking, lang:java

#1159 chore: update biomejs v1.8.1
  biome.json
  package.json
  pnpm-lock.yaml
Labels: build

#1162 Bug fix: yarn v1 dependency tree was incomplete
  deno.json
  jsr.json
  package.json
  test/data/yarn_locks/yarnv1-fs.lock
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: bug, sponsored, lang:node, yarn

#1172 python cyclic deps
  .github/workflows/nodejs.yml
  .github/workflows/repotests.yml
  README.md
  bin/cdxgen.js
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  contrib/piptree.py
  contrib/py-modules.py
  deno.json
  index.js
  jsr.json
  package.json
  piptree.js
  pnpm-lock.yaml
  test/data/pyproject-author-comma.toml
  types/evinser.d.ts
  types/index.d.ts.map
  types/piptree.d.ts.map
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: Ready for QA, possibly breaking, lang:python

#1178 Adds bzip2 to containers
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
Labels: sponsored

#1180 pnpm9 optional packages detection
  analyzer.js
  bin/repl.js
  display.js
  test/data/pnpm-lock9a.yaml
  test/data/pnpm-lock9b.yaml
  types/display.d.ts
  types/display.d.ts.map
  types/evinser.d.ts
  types/utils.d.ts
  types/utils.d.ts.map
  utils.js
  utils.test.js
Labels: enhancement, Ready for QA, pnpm

#1186 Update packages
  contrib/lima/README.md
  deno.json
  jsr.json
  package.json
  pnpm-lock.yaml
  types/db.d.ts.map
  types/evinser.d.ts
  types/evinser.d.ts.map
  types/index.d.ts.map
  types/utils.d.ts.map
  utils.test.js
Labels: Ready for QA

#1191 update python and node versions in lima
  contrib/lima/README.md
  contrib/lima/cdxgen-opensuse.yaml
Labels: documentation

#1196 Update atom to get fix for parsedeps command. Added additional unit test
  deno.json
  jsr.json
  package.json
  pnpm-lock.yaml
  test/data/requirements-lock.linux_py3.txt
  utils.test.js
Labels: Ready for QA, sponsored, possibly breaking, lang:python

#1200 Set max buffers for npm install. Print stdout in debug
  index.js
Labels: lang:node
