Repository CycloneDX/cdxgen, pull requests merged in 2025-07, with the labels that each got.

#2009 chore: GH workflow permissions
  .github/workflows/binary-builds.yml
  .github/workflows/build-images.yml
  .github/workflows/build-rolling-image.yml
  .github/workflows/codeql.yml
  .github/workflows/dockertests.yml
  .github/workflows/fix-renovate-pnpm-checksum.yml
  .github/workflows/image-build.yml
  .github/workflows/java-reachables-test.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/npm-release.yml
  .github/workflows/nydus-demo.yml
  .github/workflows/python-atom-tests.yml
  .github/workflows/rebuild-release-images.yml
  .github/workflows/repotests.yml
  .github/workflows/rerun-workflow.yml
  .github/workflows/snapshot-tests.yml
Labels: Ready for QA

#2046 Fix: Set version correctly for dotnet cpm directory packages
  bin/cdxgen.js
  biome.json
  lib/cli/index.js
  lib/helpers/utils.js
  package.json
  pnpm-lock.yaml
  types/lib/helpers/utils.d.ts.map
Labels: sponsored, lang:dotnet

#2068 windows device names check
  devenv.lock
  devenv.nix
  lib/managers/docker.js
  lib/server/server.js
  lib/server/server.test.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
  types/lib/managers/docker.d.ts.map
  types/lib/server/server.d.ts
  types/lib/server/server.d.ts.map
  uv.lock
Labels: Ready for QA, windows, mode:server, security

#2031 Fix: Enhance root dependency detection for requirements.txt
  lib/cli/index.js
  lib/helpers/utils.js
Labels: Ready for QA, lang:python

#2083 [python] re-work manifest-analysis tracker
  .github/workflows/repotests.yml
  devenv.lock
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  pnpm-lock.yaml
  test/data/issue-2069/requirements.txt
  test/data/issue-2082/requirements.txt
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
Labels: Ready for QA, lang:python

#2118 Improved query params extraction in server mode
  .github/release.yml
  .github/workflows/repotests.yml
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/server/server.js
  lib/server/server.test.js
  types/lib/helpers/utils.d.ts.map
  types/lib/server/server.d.ts
  types/lib/server/server.d.ts.map
Labels: Ready for QA, lang:dotnet, mode:server, AI-assisted
