Repository CycloneDX/cdxgen, pull requests merged in 2025-04, with the labels that each got.

#1715 Custom cache directory
  lib/cli/index.js
  types/lib/cli/index.d.ts.map
Labels: pro bono, scala

#1712 Adds support for commonjs and esbuild
  bin/cdxgen.js
  bin/verify.js
  contrib/bulk-generate/index.js
  index.cjs
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/validator.js
  lib/managers/binary.js
  package.json
  types/lib/cli/index.d.ts.map
  types/lib/helpers/validator.d.ts.map
  types/lib/managers/binary.d.ts.map
Labels: sponsored

#1724 Implementation of mill package manager -- jvm-languages only
  .github/workflows/repotests.yml
  docs/ENV.md
  docs/PROJECT_TYPES.md
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  test/data/mill/out/bar/ivyDepsTree.log
  test/data/mill/out/bar/test/ivyDepsTree.log
  test/data/mill/out/foo/ivyDepsTree.log
  test/data/mill/out/foo/test/ivyDepsTree.log
Labels: enhancement, scala

#1725 mill additional args
  ci/base-images/debian/Dockerfile.dotnet8
  ci/base-images/debian/Dockerfile.dotnet9
  lib/cli/index.js
  lib/helpers/utils.js
  lib/managers/binary.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
  types/lib/managers/binary.d.ts.map
Labels: scala

#1729 Allowlists in server mode
  deno.json
  docs/ENV.md
  docs/SERVER.md
  jsr.json
  lib/server/server.js
  package.json
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
  types/lib/server/server.d.ts.map
Labels: mode:server, security

#1738 Remove android sdk + tweaks
  .github/workflows/npm-release.yml
  .github/workflows/nydus-demo.yml
  bin/cdxgen.js
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  ci/Dockerfile-secure
  ci/base-images/README.md
  ci/base-images/sle/Dockerfile.java
  ci/base-images/sle/Dockerfile.java17
  ci/base-images/temurin/Dockerfile.java21
  contrib/cloud-init.txt
  contrib/lima/cdxgen-ubuntu.yaml
  lib/evinser/evinser.js
  lib/helpers/utils.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
Labels: breaking

#1739 [mill] Added the possibility to control usage of the server (daemon)
  docs/ENV.md
  lib/cli/index.js
Labels: scala

#1741 Ruby 3.4.3
  ci/Dockerfile
  ci/Dockerfile-deno
  ci/Dockerfile-secure
  ci/base-images/debian/Dockerfile.ruby18
  ci/base-images/debian/Dockerfile.ruby26
  ci/base-images/debian/Dockerfile.ruby33
  ci/base-images/debian/install.sh
  ci/base-images/sle/Dockerfile.ruby25
  deno.json
  lib/managers/binary.js
  package.json
  pnpm-lock.yaml
  types/lib/cli/index.d.ts.map
  types/lib/managers/binary.d.ts.map
Labels: lang:ruby

#1748 Prefix language to support multiple slices files for evinse
  .github/workflows/java-reachables-test.yml
  appimage-builder.yml
  appimage-reqs.sh
  bin/cdxgen.js
  ci/Dockerfile
  ci/Dockerfile-ppc64
  ci/base-images/cdxgen/Dockerfile.java
  ci/base-images/cdxgen/Dockerfile.node20
  ci/base-images/cdxgen/Dockerfile.python310
  ci/base-images/cdxgen/Dockerfile.python311
  ci/base-images/cdxgen/debian/Dockerfile.dotnet6
  ci/base-images/cdxgen/debian/Dockerfile.ruby26
  ci/base-images/cdxgen/temurin/Dockerfile.java21
  ci/base-images/cdxgen/temurin/Dockerfile.java8
  ci/base-images/opensuse/Dockerfile.python310
  ci/base-images/opensuse/Dockerfile.python39
  deno.json
  jsr.json
  lib/cli/index.js
  lib/evinser/evinser.js
  lib/helpers/envcontext.js
  package.json
  pnpm-lock.yaml
  types/lib/cli/index.d.ts.map
Labels: lang:node, evinse

#1751 Makes oci image export more robust when using cli
  .github/workflows/dockertests.yml
  data/component-tags.json
  data/frameworks-list.json
  lib/cli/index.js
  lib/managers/docker.js
  types/lib/cli/index.d.ts.map
  types/lib/managers/docker.d.ts.map
Labels: lang:container, lang:dotnet

#1756 [server] Additional validations + don't reflect
  bin/cdxgen.js
  deno.json
  jsr.json
  lib/server/openapi.yaml
  lib/server/server.js
  package.json
  types/lib/helpers/utils.d.ts.map
  types/lib/server/server.d.ts.map
Labels: mode:server, security

#1758 adhoc tweaks
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  ci/Dockerfile-secure
  ci/base-images/cdxgen/Dockerfile.dotnet6
  ci/base-images/cdxgen/Dockerfile.dotnet7
  ci/base-images/cdxgen/Dockerfile.dotnet8
  ci/base-images/cdxgen/debian/Dockerfile.dotnet8
  ci/base-images/opensuse/Dockerfile.lang
  ci/base-images/temurin/Dockerfile.java21
  ci/base-images/temurin/Dockerfile.java8
  data/pypi-pkg-aliases.json
  deno.json
  lib/cli/index.js
  lib/evinser/evinser.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/managers/docker.js
  lib/managers/piptree.js
  lib/stages/pregen/pregen.js
  package.json
  pnpm-lock.yaml
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts.map
  types/lib/managers/docker.d.ts.map
  types/lib/managers/piptree.d.ts.map
  types/lib/stages/pregen/pregen.d.ts.map
Labels: lang:c, evinse, mode:container

#1762 Tune down frameworks for js
  data/frameworks-list.json
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/validator.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts.map
  types/lib/helpers/validator.d.ts.map
Labels: lang:node

#1763 Create output directory if needed. Update atom to get JS improvements
  .github/workflows/nodejs.yml
  .github/workflows/repotests.yml
  bin/cdxgen.js
  deno.json
  lib/helpers/utils.test.js
  package.json
  pnpm-lock.yaml
Labels: lang:node, evinse

#1764 scan cdxgen with depscan
  .github/workflows/nodejs.yml
  lib/cli/index.js
  lib/evinser/evinser.js
  types/lib/cli/index.d.ts.map
Labels: infra, security

#1766 More container env variables
  .gitignore
  lib/cli/index.js
  types/lib/cli/index.d.ts.map
Labels: lang:container
