Repository CycloneDX/cdxgen, pull requests merged in 2025-06, with the labels that each got.

#1855 [Python] dependency tree enhancements
  .github/workflows/binary-builds.yml
  ci/Dockerfile
  ci/Dockerfile-deno
  ci/images/Dockerfile.java17
  ci/images/Dockerfile.node20
  ci/images/Dockerfile.ruby25
  ci/images/alpine/Dockerfile.ruby344
  ci/images/debian/Dockerfile.php83
  ci/images/debian/Dockerfile.ruby26
  ci/images/debian/Dockerfile.ruby33
  ci/images/debian/Dockerfile.ruby34
  ci/images/opensuse/Dockerfile.rolling
  ci/images/temurin/Dockerfile.java21
  ci/images/temurin/Dockerfile.java24
  contrib/piptree.py
  deno.json
  lib/cli/index.js
  lib/helpers/utils.js
  lib/managers/binary.js
  lib/managers/piptree.js
  package.json
  pnpm-lock.yaml
  types/lib/helpers/utils.d.ts.map
  types/lib/managers/binary.d.ts.map
  types/lib/managers/piptree.d.ts.map
Labels: sponsored, lang:python

#1863 Allowlist for server post. Quote arguments.
  .github/workflows/java-reachables-test.yml
  ci/images/debian/Dockerfile.ruby34
  devenv.lock
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/server/openapi.yaml
  lib/server/server.js
  package.json
  pnpm-lock.yaml
  types/lib/helpers/utils.d.ts.map
Labels: mode:cli, mode:server, security

#1869 musl arm64 builds
  .github/workflows/binary-builds.yml
  ci/Dockerfile
Labels: build

#1871 Move containers and containers-secure back to github-hosted
  .github/workflows/npm-release.yml
Labels: infra

#1874 feat: biomejs 2 migration
  bin/cdxgen.js
  bin/evinse.js
  bin/repl.js
  bin/verify.js
  biome.json
  contrib/bulk-generate/image-avail.js
  contrib/bulk-generate/index.js
  contrib/deno/deps.ts
  contrib/fine-tuning/prepare.js
  contrib/fine-tuning/validator.js
  lib/cli/index.js
  lib/evinser/evinser.js
  lib/evinser/evinser.test.js
  lib/evinser/swiftsem.js
  lib/evinser/swiftsem.test.js
  lib/helpers/analyzer.js
  lib/helpers/cbomutils.js
  lib/helpers/db.js
  lib/helpers/display.js
  lib/helpers/display.test.js
  lib/helpers/envcontext.js
  lib/helpers/envcontext.test.js
  lib/helpers/logger.js
  lib/helpers/protobom.js
  lib/helpers/protobom.test.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/helpers/validator.js
  lib/managers/binary.js
  lib/managers/docker.js
  lib/managers/docker.test.js
  lib/managers/oci.js
  lib/managers/piptree.js
  lib/server/server.js
  lib/stages/postgen/annotator.js
  lib/stages/postgen/annotator.test.js
  lib/stages/postgen/postgen.js
  lib/stages/postgen/postgen.test.js
  lib/stages/pregen/pregen.js
  package.json
  pnpm-lock.yaml
  test/data/package-json/v2-workspace/package.json
  test/data/package-json/v2/package.json
Labels: dependency

#1902 proto upgrade
  .github/workflows/nodejs.yml
  README.md
  bin/cdxgen.js
  bin/repl.js
  contrib/cloud-init.txt
  contrib/lima/cdxgen-ubuntu.yaml
  deno.json
  docs/CLI.md
  lib/helpers/protobom.js
  lib/helpers/protobom.test.js
  package.json
  pnpm-lock.yaml
  types/lib/helpers/protobom.d.ts.map
Labels: Ready for QA, proto

#1918 [build] Tried to optimize workflow runs even more with more detailed paths.
  .devcontainer.json
  .dockerignore
  .github/workflows/binary-builds.yml
  .github/workflows/build-images.yml
  .github/workflows/build-rolling-image.yml
  .github/workflows/codeql.yml
  .github/workflows/dockertests.yml
  .github/workflows/java-reachables-test.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/npm-release.yml
  .github/workflows/python-atom-tests.yml
  .github/workflows/repotests.yml
  .github/workflows/snapshot-tests.yml
  biome.json
Labels: Ready for QA
