Repository CycloneDX/cdxgen, pull requests merged in 2025-08, with the labels that each got.

#2133 cdx1-pro
  contrib/fine-tuning/Modelfile
  contrib/fine-tuning/README.md
  contrib/fine-tuning/convert-gguf.sh
  contrib/fine-tuning/fine-tune-mlx.sh
  contrib/fine-tuning/upload-hf.sh
Labels: ml

#2137 cdx1 8-bit xBOMEval tests
  contrib/cdx1/REPORT.md
  contrib/fine-tuning/Modelfile
  contrib/fine-tuning/README.md
  contrib/fine-tuning/convert-gguf.sh
  contrib/xBOMEval/README.md
  contrib/xBOMEval/cdx1-NOTES.md
  contrib/xBOMEval/results/README.md
  contrib/xBOMEval/results/cdx1-pro/results-0804/README.md
  contrib/xBOMEval/results/cdx1-pro/results-0804/bias-tests.png
  contrib/xBOMEval/results/cdx1-pro/results-0804/bias.json
  contrib/xBOMEval/results/cdx1-pro/results-0804/devops.json
  contrib/xBOMEval/results/cdx1-pro/results-0804/docker.json
  contrib/xBOMEval/results/cdx1-pro/results-0804/linux.json
  contrib/xBOMEval/results/cdx1-pro/results-0804/logic.json
  contrib/xBOMEval/results/cdx1-pro/results-0804/spec.json
  contrib/xBOMEval/results/cdx1/results-0805/README.md
  contrib/xBOMEval/results/cdx1/results-0805/bias.json
  contrib/xBOMEval/results/cdx1/results-0805/devops.json
  contrib/xBOMEval/results/cdx1/results-0805/docker.json
  contrib/xBOMEval/results/cdx1/results-0805/linux.json
  contrib/xBOMEval/results/cdx1/results-0805/logic.json
  contrib/xBOMEval/results/cdx1/results-0805/spec.json
  contrib/xBOMEval/results/deepseek-r1/results-0805/README.md
  contrib/xBOMEval/results/deepseek-r1/results-0805/logic.json
  contrib/xBOMEval/results/deepseek-r1/results-0805/spec.json
  contrib/xBOMEval/results/deepthink-r1/results-0805/README.md
  contrib/xBOMEval/results/deepthink-r1/results-0805/logic.json
  contrib/xBOMEval/results/deepthink-r1/results-0805/spec.json
  contrib/xBOMEval/results/gemini-2.5-pro/results-0805/README.md
  contrib/xBOMEval/results/gemini-2.5-pro/results-0805/logic.json
  contrib/xBOMEval/results/gemini-2.5-pro/results-0805/spec.json
  contrib/xBOMEval/results/gpt-oss-120b/results-0806/README.md
  contrib/xBOMEval/results/gpt-oss-120b/results-0806/logic.json
  contrib/xBOMEval/results/gpt-oss-120b/results-0806/spec.json
  contrib/xBOMEval/results/gpt-oss-20b/results-0806/README.md
  contrib/xBOMEval/results/gpt-oss-20b/results-0806/logic.json
  contrib/xBOMEval/results/gpt-oss-20b/results-0806/spec.json
  contrib/xBOMEval/results/o4-mini-high/results-0805/README.md
  contrib/xBOMEval/results/o4-mini-high/results-0805/chatgpt-spec-fail.png
  contrib/xBOMEval/results/o4-mini-high/results-0805/logic.json
  contrib/xBOMEval/results/qwen3-coder-480B/results-0805/README.md
  contrib/xBOMEval/results/qwen3-coder-480B/results-0805/logic.json
  contrib/xBOMEval/results/qwen3-coder-480B/results-0805/spec.json
  contrib/xBOMEval/sample_answers/README.md
  contrib/xBOMEval/sample_answers/logic.json
  contrib/xBOMEval/sample_answers/spec.json
  contrib/xBOMEval/tests/bias/questions.csv
  contrib/xBOMEval/tests/devops/questions.csv
  contrib/xBOMEval/tests/docker/questions.csv
  contrib/xBOMEval/tests/linux/questions.csv
  contrib/xBOMEval/tests/logic/purl1.toml
  contrib/xBOMEval/tests/logic/questions.csv
  contrib/xBOMEval/tests/spec/questions.csv
  contrib/xBOMEval/tests/standards/cyclonedx1.toml
Labels: Ready for QA, ml

#2142 cdx1 safety tests
  contrib/cdx1/REPORT.md
  contrib/xBOMEval/results/cdx1-pro/results-0804/README.md
  contrib/xBOMEval/results/cdx1-pro/results-0804/cdx1-pro-safety.png
  contrib/xBOMEval/results/cdx1/results-0805/README.md
  contrib/xBOMEval/results/cdx1/results-0805/cdx1-safety.png
  contrib/xBOMEval/tests/safety/README.md
  contrib/xBOMEval/tests/safety/questions.csv
Labels: ml

#2144 cdx1 jailbreak tests
  contrib/xBOMEval/results/cdx1-pro/results-0804/README.md
  contrib/xBOMEval/results/cdx1-pro/results-0804/cdx1-pro-jailbreak.png
  contrib/xBOMEval/results/cdx1/results-0805/README.md
  contrib/xBOMEval/results/cdx1/results-0805/cdx1-jailbreak.png
  contrib/xBOMEval/tests/safety/jailbreak-questions.csv
Labels: ml

#2146 gpt-5 benchmark
  contrib/xBOMEval/results/README.md
  contrib/xBOMEval/results/gpt-5/results-0808/README.md
  contrib/xBOMEval/results/gpt-5/results-0808/gpt-5-batch.png
  contrib/xBOMEval/results/gpt-5/results-0808/logic.json
  contrib/xBOMEval/results/gpt-5/results-0808/spec.json
Labels: ml

#2148 cdx1-mini
  contrib/fine-tuning/.gitignore
  contrib/fine-tuning/Modelfile-mini
  contrib/fine-tuning/convert-gguf.sh
  contrib/fine-tuning/fine-tune-mlx.sh
  contrib/fine-tuning/upload-hf.sh
  contrib/xBOMEval/README.md
  contrib/xBOMEval/results/README.md
  contrib/xBOMEval/results/cdx1-mini/results-0809/README.md
  contrib/xBOMEval/results/cdx1-mini/results-0809/devops.json
  contrib/xBOMEval/results/cdx1-mini/results-0809/docker.json
  contrib/xBOMEval/results/cdx1-mini/results-0809/linux.json
  contrib/xBOMEval/results/cdx1-mini/results-0809/logic.json
  contrib/xBOMEval/results/cdx1-mini/results-0809/spec.json
  contrib/xBOMEval/results/cdx1-pro/results-0804/README.md
  contrib/xBOMEval/results/cdx1-pro/results-0804/docker.json
  contrib/xBOMEval/results/cdx1/results-0805/README.md
Labels: ml

#2158 Prefer package name and version from the hint path for csproj parsing
  lib/helpers/dotnetutils.js
  lib/helpers/dotnetutils.test.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  test/data/issue-2156/demo.csproj
  types/lib/helpers/dotnetutils.d.ts
  types/lib/helpers/dotnetutils.d.ts.map
  types/lib/helpers/utils.d.ts.map
Labels: Ready for QA, breaking, lang:dotnet, test, AI-assisted

#2161 fix: dont log mvn dependency:tree args
  lib/cli/index.js
Labels: security, CWE-200
