Repository CycloneDX/cdxgen, pull requests merged in 2025-01, with the labels that each got.

#1526 [Docs] Update ENV.md to Include All Environment Variables
  docs/ENV.md
Labels: documentation

#1524 uv workspace support
  .github/workflows/snapshot-tests.yml
  ci/Dockerfile
  ci/base-images/cdxgen/Dockerfile.python
  ci/base-images/sle/Dockerfile.lang
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  test/data/pyproject_uv-workspace.toml
  test/data/uv-workspace.lock
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
Labels: sponsored, lang:python

#1528 Install Ruby 3.4.0 in container images
  .github/workflows/npm-release.yml
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  ci/base-images/sle/Dockerfile.java17
  ci/base-images/sle/Dockerfile.java17-slim
  contrib/lima/cdxgen-opensuse.yaml
  contrib/lima/cdxgen-ubuntu.yaml
  package.json
Labels: mode:container, lang:ruby

#1534 Bundle locally built cli in the container images
  ci/base-images/cdxgen/Dockerfile.dotnet6
  ci/base-images/cdxgen/Dockerfile.dotnet7
  ci/base-images/cdxgen/Dockerfile.dotnet8
  ci/base-images/cdxgen/Dockerfile.dotnet9
  ci/base-images/cdxgen/Dockerfile.java
  ci/base-images/cdxgen/Dockerfile.java-slim
  ci/base-images/cdxgen/Dockerfile.java17
  ci/base-images/cdxgen/Dockerfile.java17-slim
  ci/base-images/cdxgen/Dockerfile.node20
  ci/base-images/cdxgen/Dockerfile.python
  ci/base-images/cdxgen/Dockerfile.python310
  ci/base-images/cdxgen/Dockerfile.python311
  ci/base-images/cdxgen/Dockerfile.python36
  ci/base-images/cdxgen/Dockerfile.python39
  ci/base-images/cdxgen/Dockerfile.rolling
  ci/base-images/cdxgen/debian/Dockerfile.dotnet6
  ci/base-images/cdxgen/debian/Dockerfile.dotnet8
  ci/base-images/cdxgen/debian/Dockerfile.dotnet9
  deno.json
  jsr.json
  package.json
Labels: enhancement, possibly breaking, mode:container

#1535 container snapshot tests
  contrib/bulk-generate/README.md
  contrib/bulk-generate/index.js
  test/diff/container-tests-repos.csv
Labels: sponsored, test

#1548 Ruby 3.4.1
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  lib/cli/index.js
  lib/helpers/envcontext.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/envcontext.d.ts.map
Labels: lang:ruby, pro bono

#1549 Update atom for Ruby
  .dockerignore
  appimage-reqs.sh
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  ci/base-images/cdxgen/Dockerfile.dotnet6
  ci/base-images/cdxgen/Dockerfile.dotnet7
  ci/base-images/cdxgen/Dockerfile.dotnet8
  ci/base-images/cdxgen/Dockerfile.dotnet9
  ci/base-images/cdxgen/Dockerfile.java
  ci/base-images/cdxgen/Dockerfile.java-slim
  ci/base-images/cdxgen/Dockerfile.java17
  ci/base-images/cdxgen/Dockerfile.java17-slim
  ci/base-images/cdxgen/Dockerfile.node20
  ci/base-images/cdxgen/Dockerfile.python
  ci/base-images/cdxgen/Dockerfile.python310
  ci/base-images/cdxgen/Dockerfile.python311
  ci/base-images/cdxgen/Dockerfile.python36
  ci/base-images/cdxgen/Dockerfile.python39
  ci/base-images/cdxgen/Dockerfile.rolling
  ci/base-images/cdxgen/Dockerfile.ruby25
  ci/base-images/cdxgen/debian/Dockerfile.dotnet6
  ci/base-images/cdxgen/debian/Dockerfile.dotnet8
  ci/base-images/cdxgen/debian/Dockerfile.dotnet9
  ci/base-images/cdxgen/debian/Dockerfile.ruby33
  ci/base-images/cdxgen/debian/Dockerfile.ruby34
  ci/base-images/debian/Dockerfile.ruby33
  ci/base-images/debian/install.sh
  ci/base-images/sle/Dockerfile.ruby25
  deno.json
  jsr.json
  package.json
  pnpm-lock.yaml
Labels: lang:ruby, pro bono

#1551 Ruby 1.8 support
  .github/workflows/build-base-images.yml
  ci/base-images/README.md
  ci/base-images/debian/Dockerfile.dotnet6
  ci/base-images/debian/Dockerfile.dotnet8
  ci/base-images/debian/Dockerfile.dotnet9
  ci/base-images/debian/Dockerfile.ruby18
  ci/base-images/debian/Dockerfile.ruby33
  ci/base-images/debian/Dockerfile.ruby34
  ci/base-images/debian/install.sh
  ci/base-images/sle/Dockerfile.ruby25
  docs/ENV.md
  lib/cli/index.js
  lib/helpers/envcontext.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/envcontext.d.ts.map
Labels: lang:ruby, pro bono

#1558 Ruby repo tests
  .github/workflows/repotests.yml
  ci/base-images/README.md
  ci/base-images/cdxgen/Dockerfile.java
  data/README.md
  data/ruby-known-modules.json
  docs/ADVANCED.md
  lib/cli/index.js
  lib/evinser/evinser.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/stages/pregen/pregen.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts.map
  types/lib/stages/pregen/pregen.d.ts.map
Labels: Ready for QA, possibly breaking, lang:ruby, pro bono

#1562 Introduce atom-tools to the container images
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/base-images/cdxgen/Dockerfile.dotnet6
  ci/base-images/cdxgen/Dockerfile.dotnet7
  ci/base-images/cdxgen/Dockerfile.dotnet8
  ci/base-images/cdxgen/Dockerfile.dotnet9
  ci/base-images/cdxgen/Dockerfile.java
  ci/base-images/cdxgen/Dockerfile.java17
  ci/base-images/cdxgen/Dockerfile.node20
  ci/base-images/cdxgen/Dockerfile.python
  ci/base-images/cdxgen/Dockerfile.python310
  ci/base-images/cdxgen/Dockerfile.python311
  ci/base-images/cdxgen/Dockerfile.rolling
  ci/base-images/cdxgen/Dockerfile.ruby25
  ci/base-images/cdxgen/debian/Dockerfile.dotnet6
  ci/base-images/cdxgen/debian/Dockerfile.dotnet8
  ci/base-images/cdxgen/debian/Dockerfile.dotnet9
  ci/base-images/cdxgen/debian/Dockerfile.ruby33
  ci/base-images/cdxgen/debian/Dockerfile.ruby34
  ci/base-images/opensuse/Dockerfile.lang
Labels: mode:container

#1561 Retain and validate parent component better
  lib/cli/index.js
  lib/helpers/validator.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/validator.d.ts.map
Labels: Ready for QA, possibly breaking, lang:node, gradle

#1564 Add hash, scope and deps to dart
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  test/data/pubspec.lock
Labels: enhancement, dart

#1565 Ruby evinse improvements
  README.md
  ci/base-images/README.md
  ci/base-images/debian/Dockerfile.dotnet6
  ci/base-images/debian/Dockerfile.dotnet8
  ci/base-images/debian/Dockerfile.dotnet9
  ci/base-images/debian/Dockerfile.ruby18
  ci/base-images/debian/Dockerfile.ruby26
  ci/base-images/debian/Dockerfile.ruby33
  ci/base-images/debian/Dockerfile.ruby34
  ci/base-images/debian/install.sh
  ci/base-images/opensuse/Dockerfile.lang
  ci/base-images/opensuse/Dockerfile.python310
  ci/base-images/opensuse/Dockerfile.python39
  ci/base-images/sle/Dockerfile.dotnet6
  ci/base-images/sle/Dockerfile.dotnet7
  ci/base-images/sle/Dockerfile.dotnet8
  ci/base-images/sle/Dockerfile.dotnet9
  ci/base-images/sle/Dockerfile.java
  ci/base-images/sle/Dockerfile.java-slim
  ci/base-images/sle/Dockerfile.java17
  ci/base-images/sle/Dockerfile.java17-slim
  ci/base-images/sle/Dockerfile.lang
  ci/base-images/sle/Dockerfile.node20
  ci/base-images/sle/Dockerfile.python311
  ci/base-images/sle/Dockerfile.python36
  ci/base-images/sle/Dockerfile.ruby25
  data/ruby-known-modules.json
  lib/cli/index.js
  lib/evinser/evinser.js
  lib/helpers/envcontext.js
  lib/helpers/utils.js
  lib/managers/binary.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/envcontext.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
  types/lib/managers/binary.d.ts.map
Labels: evinse, lang:ruby

#1572 dotnet framework deep improvements
  .github/workflows/build-base-images.yml
  ci/base-images/README.md
  ci/base-images/cdxgen/Dockerfile.dotnet6
  ci/base-images/cdxgen/Dockerfile.dotnet7
  ci/base-images/cdxgen/Dockerfile.dotnet8
  ci/base-images/cdxgen/debian/Dockerfile.dotnet6
  ci/base-images/cdxgen/debian/Dockerfile.dotnet8
  ci/base-images/debian/Dockerfile.dotnet6
  ci/base-images/debian/Dockerfile.dotnet8
  ci/base-images/debian/Dockerfile.dotnet9
  ci/base-images/debian/Dockerfile.ruby18
  ci/base-images/debian/Dockerfile.ruby26
  ci/base-images/debian/Dockerfile.ruby33
  ci/base-images/debian/Dockerfile.ruby34
  ci/base-images/debian/install.sh
  ci/base-images/sle/Dockerfile.dotnet6
  lib/cli/index.js
  lib/helpers/utils.js
  lib/managers/binary.js
  types/lib/cli/index.d.ts.map
  types/lib/managers/binary.d.ts.map
Labels: lang:dotnet, mode:container

#1574 Ruby reachables test - WIP
  .github/workflows/java-reachables-test.yml
  lib/cli/index.js
  lib/evinser/evinser.js
  lib/helpers/utils.js
  lib/stages/pregen/pregen.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts.map
  types/lib/stages/pregen/pregen.d.ts.map
Labels: lang:ruby

#1575 Use docker for reachables tests
  .github/workflows/java-reachables-test.yml
  deno.json
  lib/evinser/evinser.js
  lib/stages/pregen/pregen.js
  package.json
  pnpm-lock.yaml
  types/lib/stages/pregen/pregen.d.ts.map
Labels: lang:ruby

#1578 Track pnpm workspace for each component
  deno.json
  jsr.json
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  package.json
  test/data/pnpm_locks/pnpm-workspace.yaml
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
Labels: enhancement, sponsored, pnpm

#1579 Track dev and peer dependencies as optional
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  types/lib/helpers/utils.d.ts.map
Labels: sponsored, pnpm

#1580 Track relative virtual path for workspaces
  lib/helpers/utils.js
  types/lib/helpers/utils.d.ts.map
Labels: sponsored, pnpm

#1582 Track workspaces for transitive dependencies for uv monorepos
  .github/workflows/repotests.yml
  lib/helpers/utils.js
  types/lib/helpers/utils.d.ts.map
Labels: sponsored, lang:python

#1585 workspace props validation
  lib/helpers/utils.js
  lib/helpers/validator.js
  types/lib/helpers/utils.d.ts.map
  types/lib/helpers/validator.d.ts
  types/lib/helpers/validator.d.ts.map
Labels: sponsored, lang:python

#1586 Improves dotnet dependency tree with case insensitive match
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/validator.js
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts.map
  types/lib/helpers/validator.d.ts.map
Labels: bug, sponsored, lang:dotnet

#1587 Set pnpm workspace properties recursively
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/helpers/validator.js
  types/lib/helpers/utils.d.ts.map
  types/lib/helpers/validator.d.ts.map
Labels: sponsored, pnpm

#1590 Adds is_workspace properties to uv parent components
  lib/evinser/evinser.js
  lib/helpers/utils.js
  types/lib/helpers/utils.d.ts.map
Labels: sponsored, lang:python

#1600 cdxgen secure image - WIP
  .github/workflows/npm-release.yml
  .github/workflows/repotests.yml
  bin/cdxgen.js
  bin/evinse.js
  bin/repl.js
  bin/verify.js
  ci/Dockerfile-perms
  deno.json
  docs/ENV.md
  docs/PERMISSIONS.md
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/stages/pregen/pregen.js
  package.json
  pnpm-lock.yaml
  types/lib/cli/index.d.ts.map
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
  types/lib/stages/pregen/pregen.d.ts.map
Labels: security, mode:container

#1603 Handle workspace with duplicate names
  .github/workflows/npm-release.yml
  deno.json
  jsr.json
  lib/cli/index.js
  package.json
  types/lib/cli/index.d.ts.map
Labels: sponsored, pnpm

#1609 Improved secure mode warnings
  .github/workflows/dockertests.yml
  .github/workflows/repotests.yml
  bin/cdxgen.js
  docs/PERMISSIONS.md
  lib/helpers/utils.js
  lib/helpers/utils.test.js
  lib/helpers/validator.js
  lib/server/server.js
  package.json
  types/lib/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts.map
  types/lib/helpers/validator.d.ts.map
  types/lib/server/server.d.ts.map
Labels: Ready for QA, security

#1611 update container images
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-secure
  ci/base-images/README.md
  ci/base-images/debian/Dockerfile.dotnet6
  ci/base-images/debian/Dockerfile.dotnet8
  ci/base-images/debian/Dockerfile.dotnet9
  ci/base-images/debian/Dockerfile.ruby33
  ci/base-images/debian/Dockerfile.ruby34
  ci/base-images/opensuse/Dockerfile.python310
  ci/base-images/opensuse/Dockerfile.python39
  ci/base-images/sle/Dockerfile.dotnet7
  ci/base-images/sle/Dockerfile.java
  ci/base-images/sle/Dockerfile.java-slim
  ci/base-images/sle/Dockerfile.java17
  ci/base-images/sle/Dockerfile.java17-slim
  ci/base-images/sle/Dockerfile.lang
  ci/base-images/sle/Dockerfile.node20
  ci/base-images/sle/Dockerfile.python311
  ci/base-images/sle/Dockerfile.python36
  deno.json
  docs/ENV.md
  jsr.json
  lib/helpers/envcontext.js
  lib/helpers/envcontext.test.js
  lib/helpers/utils.js
  lib/helpers/validator.js
  package.json
  types/lib/helpers/validator.d.ts.map
Labels: sponsored, mode:container
