Repository CycloneDX/cdxgen, pull requests merged in 2025-09, with the labels that each got.

#2219 Update packages
  ci/Dockerfile
  ci/Dockerfile-bun
  ci/Dockerfile-deno
  ci/Dockerfile-ppc64
  ci/images/Dockerfile.java17
  ci/images/Dockerfile.java17-slim
  ci/images/Dockerfile.python311
  ci/images/Dockerfile.python312
  ci/images/Dockerfile.python313
  ci/images/Dockerfile.python36
  ci/images/debian/Dockerfile.php83
  ci/images/debian/Dockerfile.php84
  ci/images/debian/Dockerfile.ruby26
  ci/images/debian/Dockerfile.ruby33
  ci/images/debian/Dockerfile.ruby34
  ci/images/opensuse/Dockerfile.rolling
  ci/images/temurin/Dockerfile.java21
  ci/images/temurin/Dockerfile.java24
  ci/images/temurin/Dockerfile.java8
  contrib/fine-tuning/cdxgen-docs/env.jsonl
  contrib/lima/cdxgen-opensuse.yaml
  contrib/lima/cdxgen-ubuntu.yaml
  deno.json
  devenv.lock
  docs/ENV.md
  lib/helpers/envcontext.js
  package.json
  pnpm-lock.yaml
  types/cli/index.d.ts.map
  types/helpers/utils.d.ts.map
  types/jest.config.d.ts
  types/jest.config.d.ts.map
  types/managers/docker.d.ts.map
  uv.lock
Labels: Ready for QA, dependency

#2224 Handle recursion errors while constructing the pip dependency tree
  contrib/piptree.py
  data/pypi-pkg-aliases.json
  lib/helpers/utils.js
  lib/helpers/utils.poku.js
  lib/managers/piptree.js
  test/data/extra-ml-requirements.txt
  types/helpers/utils.d.ts
  types/helpers/utils.d.ts.map
  types/managers/piptree.d.ts.map
Labels: Ready for QA, lang:python, AI-assisted

#2226 refactor: parsedList dependencies condition
  lib/cli/index.js
Labels: lang:node

#2231 Added usage of Nexus for downloading Ruby source (rbenv) when running on self-hosted runners
  .github/workflows/image-build.yml
  ci/images/Dockerfile.ruby25
  ci/images/debian/Dockerfile.ruby26
  ci/images/debian/Dockerfile.ruby33
  ci/images/debian/install.sh
Labels: build

#2237 Reverting the Debian repos on self-hosted was not correct
  ci/images/debian/Dockerfile.dotnet10
  ci/images/debian/Dockerfile.dotnet6
  ci/images/debian/Dockerfile.dotnet8
  ci/images/debian/Dockerfile.dotnet9
  ci/images/debian/Dockerfile.golang123
  ci/images/debian/Dockerfile.golang124
  ci/images/debian/Dockerfile.php83
  ci/images/debian/Dockerfile.php84
  ci/images/debian/Dockerfile.ruby26
  ci/images/debian/Dockerfile.ruby33
  ci/images/debian/Dockerfile.ruby34
  ci/images/debian/Dockerfile.rust1
  ci/images/debian/Dockerfile.swift6
Labels: build

#2239 Added usage of Nexus for downloading binaries (releases) from GitHub when running on self-hosted runners
  .github/workflows/image-build.yml
  ci/images/Dockerfile.dotnet7
  ci/images/Dockerfile.dotnet8
  ci/images/Dockerfile.java11
  ci/images/Dockerfile.java17
  ci/images/Dockerfile.java17-slim
  ci/images/Dockerfile.node20
  ci/images/Dockerfile.python311
  ci/images/Dockerfile.python312
  ci/images/Dockerfile.python313
  ci/images/Dockerfile.python36
  ci/images/debian/Dockerfile.dotnet10
  ci/images/debian/Dockerfile.dotnet6
  ci/images/debian/Dockerfile.dotnet8
  ci/images/debian/Dockerfile.dotnet9
  ci/images/debian/Dockerfile.golang123
  ci/images/debian/Dockerfile.golang124
  ci/images/debian/Dockerfile.php83
  ci/images/debian/Dockerfile.php84
  ci/images/debian/Dockerfile.ruby26
  ci/images/debian/Dockerfile.ruby33
  ci/images/debian/Dockerfile.ruby34
  ci/images/debian/Dockerfile.rust1
  ci/images/debian/Dockerfile.swift6
  ci/images/debian/install.sh
  ci/images/opensuse/Dockerfile.python310
  ci/images/opensuse/Dockerfile.python39
  ci/images/opensuse/Dockerfile.rolling
Labels: build

#2241 Added usage of Nexus for downloading Swift when running on self-hosted runners
  .github/workflows/image-build.yml
  ci/images/debian/Dockerfile.swift6
Labels: build

#2240 Added usage of Nexus for downloading Composer when running on self-hosted runners
  .github/workflows/image-build.yml
  ci/images/alpine/Dockerfile.php84
  ci/images/debian/Dockerfile.php83
  ci/images/debian/Dockerfile.php84
Labels: build

#2277 Re-added php and ruby to the binary SBOMs
  .github/workflows/binary-builds.yml
  lib/cli/index.js
Labels: bug, build

#2283 Bazel can also be downloaded from Nexus when running on self-hosted
  ci/images/Dockerfile.java11
  ci/images/Dockerfile.java17
  ci/images/Dockerfile.java17-slim
  ci/images/Dockerfile.node20
  ci/images/Dockerfile.python311
  ci/images/Dockerfile.python312
  ci/images/Dockerfile.python313
  ci/images/Dockerfile.python36
  ci/images/opensuse/Dockerfile.python310
  ci/images/opensuse/Dockerfile.python39
  ci/images/opensuse/Dockerfile.rolling
Labels: build

#2284 Found some more binary downloads that can be proxied
  .github/workflows/image-build.yml
  ci/images/Dockerfile.python311
  ci/images/opensuse/Dockerfile.python310
  ci/images/opensuse/Dockerfile.rolling
Labels: build

#2296 Switched actions to use '.nvmrc' file for Node version
  .github/workflows/binary-builds.yml
  .github/workflows/dockertests.yml
  .github/workflows/java-reachables-test.yml
  .github/workflows/nodejs.yml
  .github/workflows/npm-release.yml
  .github/workflows/nydus-demo.yml
  .github/workflows/python-atom-tests.yml
  .github/workflows/repotests.yml
Labels: build

#2295 Add yarn workspace support
  .github/workflows/repotests.yml
  lib/cli/index.js
  lib/helpers/utils.js
  lib/helpers/utils.poku.js
  lib/stages/postgen/postgen.js
  types/helpers/utils.d.ts
  types/lib/helpers/utils.d.ts
Labels: lang:node, yarn

#2311 Shaded namespace detection
  lib/helpers/utils.js
  types/helpers/utils.d.ts.map
Labels: lang:jar, needs docs

#2309 chore(renovate): configure dockerfile minor, patch, pin, digest
  renovate.json
Labels: dependency
